[tool.poetry]
name = "typer-cli"
version = "0.0.2"
description = ""
authors = ["Sebastián Ramírez <tiangolo@gmail.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
importlib_metadata = "^1.5"
typer = "^0.0.8"
click-completion = "^0.5.2"
colorama = "^0.4.3"

[tool.poetry.dev-dependencies]
pytest = "^4.4.0"
black = {version = "^19.10b0", allow-prereleases = true}
pytest-cov = "^2.8.1"
pytest-xdist = "^1.31.0"
pytest-sugar = "^0.9.2"
mypy = "^0.761"
flake8 = "^3.7.9"

[tool.poetry.scripts]
typer = "typer_cli.main:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
